In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl

In [ ]:
output_path = "report\\october"

# Customers info

In [2]:
df_customer_info = pd.read_excel("data\\customer-info\\customer-info.xlsx")
df_customer_info.head()

   CODE CUSTOMER NAME CATEGORY      ROUTE NAME   SALES_REP MERCHANDISERS
0    55     RUIRUNGU      DIST   KAMAKWA ROUTE    Lillian         Unkown
1    57      KARATINA     DIST  KARATINA ROUTE    Lillian         Unkown
2    62         RUIRU     DIST     RUIRU ROUTE  Magdaline         Unkown
3    63      MACHAKOS     DIST  MACHAKOS ROUTE       Saidi        Unkown
4    82       KANGEMI     DIST   KANGEMI ROUTE    Dorothy         Unkown

In [3]:
df_customer_info.isna().sum()

CODE             0
CUSTOMER NAME    0
CATEGORY         0
ROUTE NAME       0
SALES_REP        0
MERCHANDISERS    0
dtype: int64

In [4]:
df_customer_info.dtypes

CODE             int64
CUSTOMER NAME      str
CATEGORY           str
ROUTE NAME         str
SALES_REP          str
MERCHANDISERS      str
dtype: object

# Brands

In [ ]:
product_col = ['P', 'S', 'B', '200g','O.P.', '800g', '600g', 'MANDAZI','DOUGHNUTS', 'MANDO FAMILY PACK', '4 Square','XTRA LOONG', 'B-BITEZ']

In [ ]:
df_brands_sheetnames = pd.ExcelFile("data\\brands\\oct-week3-brand.xlsx")

In [6]:
df_brands_sheetnames.sheet_names

['Crates-inv', 'Crates-cn', 'Brands-inv', 'Brands-cn']

In [7]:
df_brands_inv = pd.read_excel("data\\brands\\oct-week3-brand.xlsx", sheet_name="Brands-inv")
df_brands_cn = pd.read_excel("data\\brands\\oct-week3-brand.xlsx", sheet_name="Brands-cn")

In [8]:
# Brands Invoice
df_brands_inv.head(2)

,Date,No,Invoice No.,A/C,Customer,P,S,B,200g,O.P.,...,600g,KATIKATI,MANDAZI,DOUGHNUTS,50-50 SLICED,MANDO FAMILY PACK,4 Square,XTRA LOONG,B-BITEZ,Qty
0,2026-10-11,2275260772,1219833,2275,MAGUNAS SUPER STORES (K) LTD - NAKURU BRANCH (...,0,30,15,0,0,...,35,0,0,0,0,0,0,0,0,110
1,2026-10-11,1270260387,1219839,1270,KIRAGU CASH SALE(1270),0,465,105,456,0,...,24,0,0,0,0,0,0,168,0,1218

In [40]:
# Brands Credits
df_brands_cn.head(2)

,Date,No,Invoice No.,A/C,Customer,P,S,B,200g,O.P.,...,600g,KATIKATI,MANDAZI,DOUGHNUTS,50-50 SLICED,MANDO FAMILY PACK,4 Square,XTRA LOONG,B-BITEZ,Qty
0,2026-10-11,2321260542,1221970,2321,OTOMATT SUPERMARKET LTD - MACHAKOS BRANCH (2321),0,-60,-30,-20,0,...,-42,0,0,0,0,0,0,0,0,-152
1,2026-10-11,2494260014,1221971,2494,MAGUNAS SUPER STORES (K) LTD - JUNCTION MALL M...,0,-30,0,-10,0,...,0,0,0,0,0,0,0,0,0,-66

In [10]:
# Generate an output after removing the credit from the invoice

# Crates

In [11]:
df_crates_inv = pd.read_excel("data\\crates\\oct-week3-crates.xlsx", sheet_name='Crates-inv')
df_crates_cn = pd.read_excel("data\\crates\\oct-week3-crates.xlsx", sheet_name='Crates-cn')

In [12]:
df_crates_inv.head()

       DATES STATUS  A/C  Invoice No.  QTY
0 2026-10-11    Inv   55     55260394   47
1 2026-10-12    Inv   55     55260395   41
2 2026-10-12    Inv   55     55260396    1
3 2026-10-13    Inv   55     55260397   43
4 2026-10-14    Inv   55     55260398   43

In [13]:
df_crates_cn.head()

       DATES STATUS  A/C  Invoice No.  QTY
0 2026-10-16     CN   55     55260402    0
1 2026-10-16     CN   55     55260403    0
2 2026-10-16     CN   55     55260404    0
3 2026-10-14     CN   57     57260409    1
4 2026-10-15     CN   57     57260410    1

In [14]:
# preprocess the data and remove the credit notes in the invoice

# Mehul Returns

In [15]:
df_mehul_rtn = pd.read_excel("data\\mehul-returns\\OCTOBER_RETURNS.xlsx", skiprows=2)
df_mehul_sheetname = pd.ExcelFile("data\\mehul-returns\\OCTOBER_RETURNS.xlsx")

In [20]:
df_mehul_sheetname.sheet_names

['1ST',
 '2ND',
 '3RD',
 'Sheet14',
 'Sheet15',
 'Sheet16',
 'Sheet17',
 'Sheet18',
 '4TH',
 '5TH',
 '6TH',
 '7TH',
 '8TH',
 'Sheet12',
 '9TH',
 '10TH',
 '12thh',
 'Sheet23',
 'Sheet24',
 'Sheet6',
 'Sheet5',
 '11TH',
 'CommentLists',
 '12TH',
 '13TH',
 '14TH',
 '15TH',
 'Sheet25',
 'Sheet26',
 'Sheet27',
 'Sheet28',
 '16TH',
 '17TH',
 '18TH',
 'Sheet19',
 'Sheet13',
 '19TH',
 '20TH',
 '21ST',
 '22ND',
 '23RD',
 '24TH',
 'Sheet11',
 'Sheet7',
 'Sheet8',
 'Sheet9',
 'APRIL RANGE',
 'MARCH RANGE ',
 'ELDORET',
 'NAKURU',
 'Sheet10',
 'Sheet1',
 'Sheet2',
 'Sheet4',
 'ALL CUSTOMERS & ROUTES',
 'DISTRIBUTORS',
 'Sheet3']

In [18]:
df_mehul_rtn.head()

,ROUTE NO,ROUTE NAME,CATEGORY,CODE,NAME,FRESH,EXP,FRESH.1,EXP.1,FRESH.2,...,EXP.8,FRESH.10,EXP.9,FRESH.11,EXP.10,FRESH.12,EXP.11,Unnamed: 31,Comments,Unnamed: 33
0,3.0,DAKAR SALES,DIST,100.0,MAJENGO,,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
1,3.0,DAKAR SALES,DIST,940.0,SHAURI MOYO -JUAKALI NRB,,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
2,3.0,DAKAR SALES,DIST,1468.0,NEW KARIOKOR DEPOT (1468),,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN
3,3.0,DAKAR SALES,DSUPMK,868.0,EASTMATT EASTLEIGH (0868),,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4,3.0,DAKAR SALES,DSUPMK,1964.0,MAGUNAS SUPER STORES (K) LTD JOGOO ROAD (1964),,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN

In [ ]:
# have different sheet name ie (1st, 2nd, 3rd, 4th etc.)

# Hansa Returns

In [24]:
df_hansa_rtn = pd.read_excel("data\\hansa-returns\\oct-week3-hansa-returns.xlsx")
df_hansa_rtn.head()

,A/C,Name,TYPE,Invoice,Date,P,S,B,200G,O.P.,...,600g,KATIKATI,MANDAZI,DOUGHNUTS,5050 SLICED,MANDO FAMILY PACK,4 Square,XTRA LOONG,BBITEZ,Qty
0,6378,NYAHURURU SALES II,RT,637826462,2026-10-11,0,6,5,12,1,...,4,0,0,0,0,0,0,0,0,28
1,6379,NYAHURURU SALES III,RT,637926411,2026-10-11,0,1,9,1,0,...,13,0,0,0,0,0,1,3,0,30
2,6372,MAUA SALES II,RT,637226310,2026-10-11,0,3,1,6,4,...,3,0,0,0,0,0,0,0,0,17
3,6374,MAUA SALES IV,RT,637426301,2026-10-11,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,2
4,6375,MAUA SALES V,RT,637526323,2026-10-11,0,14,5,2,0,...,0,0,0,0,0,0,0,0,0,21

In [ ]:
# Adding the customer info in this return

# Sales Revenue

In [ ]:
df_sales_revenue_sheetname = pd.ExcelFile("data\\sales-revenue\\Supermarket_dpts_vans_inst.xlsx")
df_sales_revenue_sheetname.sheet_names

['Invoices', 'Credits']

In [26]:
df_sales_rev_inv = pd.read_excel("data\\sales-revenue\\Supermarket_dpts_vans_inst.xlsx")
df_sales_rev_cn = pd.read_excel("data\\sales-revenue\\Supermarket_dpts_vans_inst.xlsx")

In [ ]:
df_sales_rev_inv.columns = df_sales_rev_inv.columns.str.replace(".", "").str.replace(" ", "_")
df_sales_rev_cn.columns = df_sales_rev_cn.columns.str.replace(".", "").str.replace(" ", "_")

In [39]:
df_sales_rev_inv.head(2)

,Date,No,Invoice_No,A/C_No,Customers,Category,Route,Qty,Total_Amt,Vat_Amt,Extra_Cts,Amount
0,2026-01-01,1964260001,855312,1964,MAGUNAS SUPER STORES (K) LTD JOGOO ROAD (1964),DSUPMK,DAKAR SALES,77.0,4487.0,0.0,0.0,4487.0
1,2026-01-01,1501260001,855314,1501,MAJID AL FUTTAIM - THE JUNCTION (1501),DSUPMK,WAITHAKA 1 ROUTE,140.0,10219.0,0.0,0.0,10219.0